theme = "slick"
icons = "awesome"

[[block]]
block="backlight"
[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"
[[block]]
block="battery"
interval= 10
format = "{percentage}%"

[[block]]
block = "time"
interval = 10
format = "%a %d/%m %R"

